resources:
 pipelines:
   - pipeline: 'build_from_maven_build'
     source: 'Vikramanr90.adorepo'
     trigger: true

pool:
  name: vikram-first-self-agent-pool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    pipeline: build_from_maven_build
    artifactName: 'maven_build_artifact'
    targetPath: '/home/adoagentuser/adoagent/_work/4-vikram'